<?php
use \Drupal\node\NodeInterface;
use \Drupal\Core\Session\AccountInterface;
use \Drupal\Core\Access\AccessResult;

function iq_pb_cug_node_access($node, $op, $account)
{
    if ($op == 'view' && $node->bundle() == 'iqbm_page') {
        $roleField = $node->field_iqcg_extranet;
        if ($roleField->count() > 0) {
            $iterator = $roleField->getIterator();
            $roles = [];
            while ($iterator->valid()) {
                $roles[] = $iterator->current()->target_id;
                $iterator->next();
            }
            if (count(array_intersect($roles, $account->getRoles())) > 0) {
                return AccessResult::allowed()->cachePerPermissions();
            } else {
                return AccessResult::forbidden()->cachePerPermissions();
            }
        }
    }
    return AccessResult::neutral();
}

/**
 * Implements hook_form_alter().
 */
function iq_pb_cug_form_alter(&$form, \Drupal\Core\Form\FormStateInterface\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Alter login form and add own custom submit handler.
    case 'user_login_form':
        $form['#submit'][] = '_iq_pb_cug_user_login_form_submit';
        break;
  }
}

/**
 * Custom submit handler for login form.
 */
function _iq_pb_cug_user_login_form_submit($form, FormStateInterface $form_state) {
  // Set redirect to login form.
    $user = \Drupal::currentUser(); 
    if (in_array('Extranet', $user->roles)) {
        $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => 4096]);
        $form_state->setRedirect($url);
    }
}