# Schema for the configuration files of the captcha module.
#wrong_response_counter

iq_pb_cug.settings:
  type: config_object
  label: 'iQual CUG'
  mapping:
    cug_redirection:
      type: mapping
      label: 'CUG Redirection'
      mapping:
        role:
          type: string
          label: 'Role'
        cug_url:
          type: string
          label: 'Redirect to URL'
    default_redirection:
      type: string
      label: 'The default redirection for all roles.'
    login_destination:
      type: string
      label: 'The login destination for all roles.'
